### ISSUE TITLE
admin-ui install failure on raspberry pi: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x

### ISSUE THREAD

**Issue by ph1l** [tkurki/marinepi-provisioning#45]
> pi@marinepi:/opt/signalk-server/admin-ui $ (npm run clean && npm run build) 2>&1 | tee /tmp/failure.log

```
ERROR in ./node_modules/css-loader?{"alias":{"../img":"../public_src/img"}}!./node_modules/sass-loader/lib/loader.js!./scss/style.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.1
    at module.exports (/opt/signalk-server/admin-ui/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/opt/signalk-server/admin-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/signalk-server/admin-ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/opt/signalk-server/admin-ui/node_modules/webpack/lib/Compilation.js:151:10)
    at factoryCallback (/opt/signalk-server/admin-ui/node_modules/webpack/lib/Compilation.js:344:12)
    at factory (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
 @ ./scss/style.scss 4:14-127 18:2-22:4 19:20-133
 @ ./src/index.js
 @ multi ./src/index.js
```
full log: [failure.log](https://github.com/SignalK/signalk-server-node/files/1820338/failure.log)

**Comment by ph1l** [comment]
see also: signalk/signalk-server-node#480

**Comment by tkurki** [comment]
I tried provising on top of a custom Stretch Lite and did not get errors, just RPi3 sitting in node-gyp and eventually swapping. Left it there overnight and Ansible ssh connection had dropped. 

I don't think this is really worth fixing like this, but the problem remains: how do you get the web apps if you want git installation of the server? I think the proper solution is to have them in the server repo, but by default installed from npm. Then if you want to develop stuff that involves server api & admin changes for example you can link them locally and release at the same time.

**Comment by ph1l** [comment]
I think this can be closed
